import { test, expect } from '@playwright/test';
import path from 'node:path';

test('desktop: account, PDF upload, viewer, comments, guest access, revocation', async ({ page, browser }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Make room for clarity.' })).toBeVisible();
  await page.screenshot({ path: 'artifacts/auth-desktop.png', fullPage: true });
  const email = `browser-${Date.now()}@example.com`;
  await page.getByLabel('Full name', { exact: true }).fill('Alex Morgan');
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('A-strong-test-password-42!');
  await page.getByRole('button', { name: 'Create workspace', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your document workspace.' })).toBeVisible();
  await page.screenshot({ path: 'artifacts/dashboard-empty.png', fullPage: true });
  await page.getByRole('button', { name: 'Upload PDF', exact: true }).click();
  await page.locator('input[type=file]').setInputFiles(path.resolve('public/samples/service-agreement.pdf'));
  await page.getByRole('button', { name: 'Upload & understand' }).click();
  await expect(page.getByRole('heading', { name: 'service-agreement.pdf', exact: true })).toBeVisible();
  await page.screenshot({ path: 'artifacts/dashboard-document.png', fullPage: true });
  await page.getByRole('button', { name: 'Open service-agreement.pdf', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'service-agreement', exact: true })).toBeVisible();
  await expect(page.locator('.pdf-rendering')).not.toBeVisible();
  await expect(page.locator('.pdf-error')).toHaveCount(0);
  await expect(page.locator('.pdf-paper > canvas')).toBeVisible();
  await expect(page.locator('.pdf-text-layer')).toContainText('MASTER SERVICES AGREEMENT');
  await page.getByRole('button', { name: 'Next page', exact: true }).click();
  await expect(page.locator('.pdf-text-layer')).toContainText('COMMERCIAL TERMS');
  await page.screenshot({ path: 'artifacts/viewer-desktop.png', fullPage: true });
  await page.getByRole('tab', { name: /Comments/ }).click();
  await page.getByRole('textbox', { name: 'Write a comment', exact: true }).fill('**Please confirm** the payment schedule.');
  await page.getByRole('button', { name: 'Post', exact: true }).click();
  await expect(page.locator('.comment .markdown strong')).toHaveText('Please confirm');
  await page.getByRole('button', { name: 'Share document', exact: true }).click();
  await page.getByLabel('Invitation name').fill('Finance team');
  await page.getByRole('button', { name: 'Create secure link', exact: true }).click();
  await expect(page.getByLabel('Copy this link now')).toHaveValue(/\/share#/);
  const link = await page.getByLabel('Copy this link now').inputValue();
  await page.screenshot({ path: 'artifacts/share-dialog.png', fullPage: true });
  const guestContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const guest = await guestContext.newPage(); await guest.goto(link);
  await expect(guest.getByText('Guest access', { exact: true })).toBeVisible();
  await expect(guest.locator('.pdf-rendering')).not.toBeVisible();
  await guest.getByRole('tab', { name: /Comments/ }).click();
  await expect(guest.getByText('Please confirm', { exact: true })).toBeVisible();
  await guest.getByRole('button', { name: 'Reply', exact: true }).click();
  await guest.getByRole('textbox', { name: 'Your name for comments' }).fill('Priya Shah');
  await guest.getByRole('textbox', { name: 'Write a comment', exact: true }).fill('Confirmed: 40% at signing, then 30% at design approval and delivery.');
  await guest.getByRole('button', { name: 'Post', exact: true }).click();
  await expect(guest.getByText('Priya Shah (guest)', { exact: true })).toBeVisible();
  await guest.screenshot({ path: 'artifacts/guest-comments.png', fullPage: true });
  await page.getByRole('button', { name: 'Revoke Finance team' }).click();
  await guest.reload(); await expect(guest.getByRole('heading', { name: 'This document is unavailable.' })).toBeVisible();
  await guestContext.close();
  expect(errors).toEqual([]);
});

test('mobile: readable account flow, dashboard, upload and PDF reader', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/');
  await page.screenshot({ path: 'artifacts/auth-mobile.png', fullPage: true });
  await page.getByLabel('Full name', { exact: true }).fill('Jordan Lee'); await page.getByLabel('Email address').fill(`mobile-${Date.now()}@example.com`);
  await page.getByLabel('Password', { exact: true }).fill('A-strong-test-password-42!'); await page.getByRole('button', { name: 'Create workspace', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your document workspace.' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/dashboard-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Try a sample' }).click();
  await expect(page.getByRole('heading', { name: 'Northstar — Service Agreement.pdf', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open Northstar — Service Agreement.pdf', exact: true }).click();
  await expect(page.locator('.pdf-text-layer')).toContainText('MASTER SERVICES AGREEMENT');
  await expect(page.locator('.pdf-rendering')).not.toBeVisible(); await expect(page.locator('.pdf-paper > canvas')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/viewer-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Chat & comments', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'Ask a question about this PDF' })).toBeVisible();
  await page.screenshot({ path: 'artifacts/chat-mobile.png', fullPage: true });
});
